
[theme]
base="light"
backgroundColor="#fef9fc"
secondaryBackgroundColor="lavenderblush"
codeBackgroundColor="plum"

[theme.sidebar]
backgroundColor="lavenderblush"
secondaryBackgroundColor="#f4d4de"
